# 开发环境配置
# 项目相关配置
st:
  # 名称
  name: st
  # 版本
  version: 1.0
  # 版权年份
  copyrightYear: 2020
  # 文件路径
  profile: D:/st/
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  # 服务端口
  port: 9003
  # 项目contextPath
  context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    # Tomcat启动初始化的线程数，默认值25
    threads:
      min-spare: 2
      max: 20


# 日志配置
logging:
  config: classpath:logback.xml
#  level:
#      com.st.demo.mapper: error #打印sql

# Spring配置
spring:
  session:
    store-type: none
  application:
      name: st

  datasource:
    Driver: com.mysql.jdbc.Driver
    username: stest
    password: stest123
    url: jdbc:mysql://152.136.234.157:31406/stest?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  defaultCount: false

# MyBatis
mybatis:
#    # 搜索指定包别名
    typeAliasesPackage: com.st.demo.mapper
#    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/*Mapper.xml
#    # 加载全局的配置文件
#    configLocation: classpath:mapper/mybatis-config.xml
